### ISSUE TITLE
Preserve Folder Numbering Prefix

### ISSUE THREAD

**Issue by qazero** [turulix/obsidian-folder-index#44]
I have a bunch of folders in my vault, some of which have numbers prefixed as seen in the screenshot below. Would it be possible to detect if there is any numbering prefixed in the folder names and if so respect the numbering used? For example, in the screenshot below, my folder number begins at the number 0 but the automatically generated MOC begins at 1. In addition, if I rename my folder to begin at the number 1 instead of 0, the MOC would have 2 numbers prefixed as seen in the screenshot below. Would it be possible to detect these instances to prevent numbers to be prepended in cases where folders already have a number prefixed?

Alternatively, would it be possible to define custom ordering/numbers in the settings for the plugin where we can define the number to prefix parent folders? If a folder is not mentioned in the settings then we can assign the next ascending number.

![image](https://user-images.githubusercontent.com/10906010/235832806-3075540b-1c2f-41e8-922e-f6b51399809f.png)

**Comment by turulix** [comment]
The Problem with that is, the list is just generated markdown, so I can't really affect the number shown as thats done by Obsidian. I could check if the name starts with a number and remove it in the name. Alternativly with the next release there will be an option to use bulletlists instead of the numbers, would that be helpfull?

Also, I love that theme where do I get it?

**Comment by turulix** [comment]
Just implemented #10 maybe that could help you

**Comment by qazero** [comment]
Sweet, thanks! I was trying to test it out but Obsidian keeps failing to update. Possibly an issue with the manifest.json again?

I'm using the Blue Topaz theme :)

![image](https://user-images.githubusercontent.com/10906010/236005358-e8060938-9c82-467c-be63-90145ebe8590.png)

**Comment by qazero** [comment]
Probably not the manifest.json I'm getting a 404 again for some reason.

```app.js:1 Error: Request failed, status 404
    at new t (app.js:1:1668026)
    at tU (app.js:1:1668218)
    at app.js:1:1668895
    at app.js:1:235927
    at Object.next (app.js:1:236032)
    at a (app.js:1:234750)
(anonymous) @ app.js:1
```

**Comment by qazero** [comment]
Not sure what the issue was but was finally able to update. Excited to test this out, thanks again!

**Comment by turulix** [comment]
Me beimg stupid was the issue xD

**Comment by qazero** [comment]
> Just implemented #10 maybe that could help you

Hmm I haven't had much luck with the plugin mentioned in #10. I opened an issue on the developer's Github: https://github.com/snezhig/obsidian-front-matter-title/issues/111

Have you gotten it to work? Not sure if your use-case is different as the one mentioned in my issue linked above.
